; PlatformIO Project Configuration File for OnStepX
; OnStepX Arduino project structure

[platformio]
src_dir = .
include_dir = src

[env:esp32dev]
platform = espressif32@6.9.0  ; ESP32 Arduino Core 2.0.17
board = esp32dev
framework = arduino

; Library dependencies
; lib_deps =
;     Wire
;     https://github.com/Makuna/Rtc/archive/refs/tags/2.3.5.zip
;     https://github.com/hjd1964/TMC2209.git
;     https://github.com/teemuatlut/TMCStepper/archive/refs/heads/master.zip
;     https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git
;     https://github.com/hjd1964/OneWire/archive/refs/heads/master.zip

lib_extra_dirs = ~/Documents/Arduino/libraries

; Board configuration
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv

; Upload/Monitor settings
upload_speed = 921600
upload_port = COM3 # needs to be your port in your BS. Windows: COMx. In WSL2 this could be mapped using usbip
monitor_speed = 115200
monitor_echo = yes